title: MDS draft
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "makedatashine" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Make Data Shine  # Credits: David Freeman for the theme and the template
author-img: mds-logo.jpg # add your photo
about-author: TODO # add description
social-twitter: makedatashine # add your Twitter handle
social-facebook: makedatashine # add your Facebook handle
social-github: makedatashine # add your Github handle
social-linkedin: makedatashine # add your Linkedin handle
social-email: contact@makedatashine.com # add your Email address

# Disqus
discus-identifier: bryukh # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
